apiVersion: v1
kind: Namespace
metadata:
  name: blog-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: blog-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: blog-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-system

