apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-dev
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-postgres
  namespace: blog-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-redis
  namespace: blog-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-frontend
  namespace: blog-dev
imagePullSecrets:
  - name: ghcr-pull

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-stage
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-postgres
  namespace: blog-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-redis
  namespace: blog-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-frontend
  namespace: blog-stage
imagePullSecrets:
  - name: ghcr-pull


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-prod
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-postgres
  namespace: blog-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-redis
  namespace: blog-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-frontend
  namespace: blog-prod
imagePullSecrets:
  - name: ghcr-pull
