apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-prod
