apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-postgres
  namespace: blog-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-redis
  namespace: blog-dev
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-postgres
  namespace: blog-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-redis
  namespace: blog-stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-backend
  namespace: blog-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-postgres
  namespace: blog-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-redis
  namespace: blog-prod
