apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

images:
- name: backend-image
  newTag: 40a3009fecc0ab74dd341978ee9f37ddf8771742