apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base

images:
  - name: frontend-image
    newName: ghcr.io/blogpostplatform/frontend
    newTag: latest
