apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base

images:
  - name: frontend-image
    newName: ghcr.io/blogpostplatform/frontend
    newTag: dev-sha-3e8068735e290781b0dacddb3b0d08eb1490b9e8-run-31540680643-1
