apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: vault-access=backend
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1role
        value: blog-dev-backend
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-backend.env
        value: blog-post/data/dev/backend
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-redis.env
        value: blog-post/data/dev/redis
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-postgres.env
        value: blog-post/data/dev/postgres

  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: vault-access=redis
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1role
        value: blog-dev-redis
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-redis.env
        value: blog-post/data/dev/redis

  - target:
      group: apps
      version: v1
      kind: StatefulSet
      labelSelector: vault-access=postgres
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1role
        value: blog-dev-postgres
      - op: add
        path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-postgres.env
        value: blog-post/data/dev/postgres


images:
- name: backend-image
  newName: ghcr.io/blogpostplatform/backend
  newTag: sha-1d84de98c6c14f819a67a17db4ae27d7b56caab1
