apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

images:
- name: backend-image
  newName: ghcr.io/blogpostplatform/backend
  newTag: sha-f09116cf0dfb4b2fed2dff3f1ffde0b66e9515c6
