apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

images:
- name: backend-image
  newName: ghcr.io/blogpostplatform/backend
  newTag: sha-530475bd668c346a851354f53061d9536efbde3d
