apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: blog
spec:
  serviceAccountName: blog-post-service-account
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
