apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: db
    vault-access: postgres
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/auth-path: "auth/blog-post-kubernetes"
        vault.hashicorp.com/agent-inject-token-audience: "vault"
    spec:
      serviceAccountName: blog-postgres
      containers:
        - name: postgres
          image: postgres:18
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: 
           - |
             set -a
             . /vault/secrets/postgres.env
             set +a
             exec docker-entrypoint.sh postgres


          ports:
            - containerPort: 5432

          volumeMounts:
           - name: postgres-data
             mountPath: /var/lib/postgresql

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"            
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc 